name: 'atm_project'
version: '1.0.0'
config-version: 2

profile: 'atm_project'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  atm_project:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
